server:
  port: 8080
spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: producer-service-event
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer